name: Windows and WebGL Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildForWindows:
    name: Build For Windows
    runs-on: windows-latest
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Windows
      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Win64
          projectPath: .
      - uses: actions/upload-artifact@v3
        with:
          name: build-Windows
          path: build/Windows

  buildForWebGL:
    name: Build For WebGL
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL
      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          projectPath: .
      - uses: actions/upload-artifact@v3
        with:
          name: build-WebGL
          path: build/WebGL 